#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("homework_helper.Resource", IsApplication=true)]

namespace homework_helper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int buttonAnswerPath = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int buttonAskPath = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int buttonFbSignIn = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int checkToDoItem = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int imageLogo = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout2 = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int listViewQuestion = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int menu_refresh = 2131165198;
			
			// aapt resource value: 0x7f070009
			public const int textPathQuestion = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int textQuestionAuthor = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int textQuestionHeader = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int textQuestionPoint = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int textViewMyQuestions = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textViewQuestions = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int QuestionList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int QuestionListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Row_List_To_Do = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SelectPath = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int add_button_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int add_textbox_hint = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int answer_text = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int ask_text = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int login_button_text = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int mobile_services = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int path_question_text = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int view_my_question_text = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int view_question_text = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
